version: '3'

services:
  goapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'workshop-goapp'
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on: 
      - mongo
    links:
      - mongo
    environment:
      ENV: development
      PORT: 5000
      DB_MONGO_URI: mongodb://mongo:27017
      DB_MONGO_DBNAME: workshop
    networks:
      - goworkshop

  mongo:
    image: "mongo"
    container_name: "workshop-mongo"
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017
      - 29017:27017
    networks:
      - goworkshop


networks:
  goworkshop:
